export default REPOSITORY_FETCH_REQUESTED = 'REPOSITORY_FETCH_REQUESTED'
export default REPOSITORY_FETCH_SUCCEEDED = 'REPOSITORY_FETCH_SUCCEEDED'
export default REPOSITORY_FETCH_FAILED = 'REPOSITORY_FETCH_FAILED'
