export const REPOSITORY_FETCH_REQUESTED = 'REPOSITORY_FETCH_REQUESTED'
export const REPOSITORY_FETCH_SUCCEEDED = 'REPOSITORY_FETCH_SUCCEEDED'
export const REPOSITORY_FETCH_FAILED = 'REPOSITORY_FETCH_FAILED'
